# --- Basic options --- #

# Name of website
title: Julie Herry

# Short description of your site
description: Mon portfolio d'artiste

# Your name to show in the footer
author: Julie Herry

# --- List of links in the navigation bar --- #

navbar-links:
  Dessins:
    - Par la fenêtre: "images/fenetres"
    - Jardinières: "images/jardinieres"
    - Poubelles: "images/poubelles"
  Peintures:
    - Routes: "images/routes"
  Expos: "expositions"
  A propos de moi: "apropos"

# --- Logo --- #

# Image to show in the navigation bar - works best with a square image
# Remove this parameter if you don't want an image in the navbar
# avatar: "/assets/img/julie.jpg"

# By default, the image is cut into a circle. You can disable this behaviour here.
# round-avatar: true

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image


# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
  email: "julieherry@yahoo.fr"
  instagram: julieherry
  rss: false
#  reddit: yourname
#  linkedin: daattali
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname
#  telegram: yourname
#  calendly: yourname

# --- General options --- #

# Select which social network share links to show in posts
share-links-active:
  instagram: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "julieherry.com"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# Personalize the colors in your website. Colour values can be any valid CSS colour

navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
link-col: "#008AFF"
hover-col: "#0085A1"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
# instead of colour

#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
#google_analytics: ""

# Google Tag Manager ID
#gtm: ""

gallery:
  dir: images               # Path to the gallery
  symlink: false            # false: copy images into _site. true: create symbolic links (saves disk space)
  title: ""           # Title for gallery index page
  title_prefix: ""  # Title prefix for gallery pages. Gallery title = title_prefix + gallery_name
  sort_field: "date_time"   # How to sort galleries on the index page.
                            # Possible values are: title, date_time, best_image
  thumbnail_size:
    x: 400                  # max width of thumbnails (in pixels)
    y: 400                  # max height of thumbnails (in pixels)
  # The following options are for individual galleries.
  galleries:
    jardinieres:
      name: "Jardinières"
      images: 
        jardinieres.1.jpg:
          dimension: "A4"
          title: "Jardinière 1"
        jardinieres.2.jpg:
          dimension: "A4"
          title: "Jardinière 2"
        jardinieres.3.jpg:
          dimension: "A4"
          title: "Jardinière 3"
        jardinieres.4.jpg:
          dimension: "A4"
          title: "Jardinière 4"
    fenetres:
      name: "Fenetres"
      images: 
        jean.dupont.1.jpg:
          dimension: "A4"
          title: "Par la fenêtre de @jean.dupont"
        jean.dupont.2.jpg:
          dimension: "A4"
          title: "Par la fenêtre de @jean.dupont"
        jean.dupont.3.jpg:
          dimension: "A4"
          title: "Par la fenêtre de @jean.dupont"
        jean.dupont.4.jpg:
          dimension: "A4"
          title: "Par la fenêtre de @jean.dupont"
        jean.dupont.5.jpg:
          dimension: "A4"
          title: "Par la fenêtre de @jean.dupont"
    poubelles:
      name: "Poubelles"
      images: 
        poubelles.1.jpg:
          dimension: "A4"
          title: "Poubelle 1"

# Matomo (aka Piwik) Web statistics
# Uncomment the following section to enable Matomo. The opt-out parameter controls
# whether or not you want to allow users to opt out of tracking.
#matomo:
#  site_id: "9"
#  uri: "demo.wiki.pro"
#  opt-out: true

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# To use Utterances comments: (0) uncomment the following section, (1) fill in
# "repository" (make sure the repository is public), (2) Enable Issues in your repository,
# (3) Install the Utterances app in your repository https://github.com/apps/utterances
# See more details about the parameters below at https://utteranc.es/
#utterances:
#  repository: # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  issue-term: title   # Mapping between blog posts and GitHub issues
#  theme: github-light # Utterances theme
#  label: blog-comments # Label that will be assigned to GitHub Issues created by Utterances

# To use Staticman comments, first invite `staticmanlab` as a collaborator to your repository and
# accept the invitation by going to `https://staticman3.herokuapp.com/v3/connect/github/<username>/<repo-name>`.
# Then uncomment the following section and fill in "repository", "branch", and "endpoint".
# If you want to use reCaptcha for staticman (optional for spam protection), then fill
# in the "siteKey" and "secret" parameters below and also in `staticman.yml`.
# See more details at https://staticman.net/
#staticman:
#  repository : # GitHub username/repository eg. "daattali/beautiful-jekyll"
#  branch     : master # If you're not using `master` branch, then you also need to update the `branch` parameter in `staticman.yml`
#  endpoint   : # URL of your own deployment, with a trailing slash (will fallback to a public GitLab instance) eg. https://<your-api>/v3/entry/github/
#  reCaptcha:
#    siteKey  : # Use your own site key, you need to apply for one on Google
#    secret   : # ENCRYPT your password by going to https://staticman3.herokuapp.com/v3/encrypt/<your-site-secret>

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%B %-d, %Y"

# Facebook App ID
#fb_app_id: ""


# --- You don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "Europe/Paris"
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5

kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
      readtime: false # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true


# Exclude these files from production site
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - screenshot.png
  - docs/

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gallery-generator
  